"""initial tables

Revision ID: f7d3a84be1ff
Revises: 
Create Date: 2026-02-21 16:12:07.782134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d3a84be1ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建 products 表
    op.create_table('products',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('sku', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_products_name', 'products', ['name'], unique=False)
    op.create_unique_constraint('uq_products_sku', 'products', ['sku'])
    
    # 创建 product_stocks 表
    op.create_table('product_stocks',
        sa.Column('product_id', sa.BigInteger(), nullable=False),
        sa.Column('available_stock', sa.Integer(), server_default='0', nullable=False),
        sa.Column('reserved_stock', sa.Integer(), server_default='0', nullable=False),
        sa.Column('version', sa.Integer(), server_default='0', nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('product_id'),
        sa.CheckConstraint('available_stock >= 0', name='ck_available_stock_non_negative'),
        sa.CheckConstraint('reserved_stock >= 0', name='ck_reserved_stock_non_negative')
    )
    
    # 创建 inventory_reservations 表
    op.create_table('inventory_reservations',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('order_id', sa.String(length=64), nullable=False),
        sa.Column('product_id', sa.BigInteger(), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('RESERVED', 'CONFIRMED', 'RELEASED', 'CANCELED', name='reservation_status_type', create_type=True), server_default='RESERVED', nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column('expired_at', sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_reservations_order_id', 'inventory_reservations', ['order_id'], unique=False)
    op.create_index('idx_inventory_reservations_product_id', 'inventory_reservations', ['product_id'], unique=False)
    op.create_index('idx_reservation_product_status', 'inventory_reservations', ['product_id', 'status'], unique=False)
    op.create_unique_constraint('uq_order_product', 'inventory_reservations', ['order_id', 'product_id'])
    
    # 创建 inventory_logs 表
    op.create_table('inventory_logs',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('product_id', sa.BigInteger(), nullable=False),
        sa.Column('order_id', sa.String(length=64), nullable=True),
        sa.Column('change_type', sa.Enum('RESERVE', 'CONFIRM', 'RELEASE', 'ADJUST', name='inventory_change_type', create_type=True), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('before_available', sa.Integer(), nullable=False),
        sa.Column('after_available', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column('operator', sa.String(length=64), nullable=True),
        sa.Column('source', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inventory_logs_order_id', 'inventory_logs', ['order_id'], unique=False)
    op.create_index('idx_inventory_logs_product_id', 'inventory_logs', ['product_id'], unique=False)
    op.create_index('idx_inventory_logs_product_created_desc', 'inventory_logs', ['product_id', sa.desc('created_at')], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_inventory_logs_product_created_desc', table_name='inventory_logs')
    op.drop_index('idx_inventory_logs_product_id', table_name='inventory_logs')
    op.drop_index('idx_inventory_logs_order_id', table_name='inventory_logs')
    op.drop_table('inventory_logs')
    
    op.drop_index('idx_reservation_product_status', table_name='inventory_reservations')
    op.drop_index('idx_inventory_reservations_product_id', table_name='inventory_reservations')
    op.drop_index('idx_inventory_reservations_order_id', table_name='inventory_reservations')
    op.drop_constraint('uq_order_product', 'inventory_reservations', type_='unique')
    op.drop_table('inventory_reservations')
    
    op.drop_table('product_stocks')
    
    op.drop_index('idx_products_name', table_name='products')
    op.drop_constraint('uq_products_sku', 'products', type_='unique')
    op.drop_table('products')
    # ### end Alembic commands ###
